### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by mariopossamato** [friedkeenan/nx-hbc#5]
Almost certainly a problem on my end, but I'm receiving this error:
```
nx-hbc/source/apps.c:7:10: fatal error: libconfig.h: No such file or directory
    7 | #include <libconfig.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [C:\devkitPro/devkitA64/base_rules:19: apps.o] Error 1
make: *** [Makefile:173: build] Error 2
```
Building with devkitPro MSYS2 on Windows 11.

**Comment by friedkeenan** [comment]
This project is no longer active or supported, I make no promises as to it being able to build and currently will not put effort towards it.

However, your issue seems to be that you don't have switch-libconfig installed.
